const std = @import("std");
const codegen = @import("codegen");
const gherkin = codegen.gherkin_mod;

const Allocator = std.mem.Allocator;

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const aio = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len < 3) return error.Usage;
    const features_path = args[1];
    const out_path = args[2];
    var tag_text: ?[]const u8 = null;
    var ai: usize = 3;
    while (ai < args.len) : (ai += 1) {
        if (std.mem.eql(u8, args[ai], "--tags") and ai + 1 < args.len) {
            ai += 1;
            const text = std.mem.trim(u8, args[ai], &std.ascii.whitespace);
            if (text.len > 0) tag_text = text;
        }
    }

    // Parsed once, before the walk, so a malformed expression is reported
    // against the option it came from rather than per scenario.
    var filter: ?codegen.TagFilter = null;
    if (tag_text) |text| filter = codegen.TagFilter.parse(arena, text) catch |err| die(
        "-Dtags=\"{s}\" is not a tag expression: {s}\n" ++
            "  a tag expression is @tag, not, and, or and parentheses, as in \"@smoke and not @slow\"",
        .{ text, @errorName(err) },
    );

    const cwd: ?[]const u8 = std.process.currentPathAlloc(aio, arena) catch null;
    const searched = try relativize(arena, cwd, features_path);

    var in_dir = std.Io.Dir.cwd().openDir(aio, features_path, .{ .iterate = true }) catch |err| die(
        "cannot open the features directory {s}: {s}",
        .{ searched, @errorName(err) },
    );
    defer in_dir.close(aio);
    var out_dir = std.Io.Dir.cwd().openDir(aio, out_path, .{}) catch |err| die(
        "cannot open the output directory {s}: {s}",
        .{ out_path, @errorName(err) },
    );
    defer out_dir.close(aio);

    var walker = try in_dir.walk(arena);
    var names: std.ArrayList([]const u8) = .empty;
    while (try walker.next(aio)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".feature")) continue;
        try names.append(arena, try arena.dupe(u8, entry.path));
    }
    std.mem.sort([]const u8, names.items, {}, struct {
        fn lt(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.lt);

    var root: std.ArrayList(u8) = .empty;
    try root.appendSlice(arena, "test {\n");
    var tests: usize = 0;
    var rejected = false;
    for (names.items, 0..) |name, i| {
        const path = try relativize(arena, cwd, try std.fs.path.join(arena, &.{ features_path, name }));
        const source = in_dir.readFileAlloc(aio, name, arena, .unlimited) catch |err| die(
            "cannot read {s}: {s}",
            .{ path, @errorName(err) },
        );
        var parse_diag: gherkin.Diagnostic = undefined;
        var emit_diag: codegen.Diagnostic = undefined;
        const generated = blk: {
            const feature = gherkin.parse(arena, path, source, &parse_diag) catch {
                rejected = true;
                break :blk try rejection(arena, path, parse_diag);
            };
            const emitted = codegen.emit(arena, feature, filter, &emit_diag) catch |err| switch (err) {
                error.OutOfMemory => return err,
                else => {
                    rejected = true;
                    break :blk try rejection(arena, path, emit_diag);
                },
            };
            tests += emitted.tests;
            break :blk emitted.source;
        };
        const out_name = try std.fmt.allocPrint(arena, "f{d}.zig", .{i});
        try out_dir.writeFile(aio, .{ .sub_path = out_name, .data = generated });
        try root.print(arena, "    _ = @import(\"{s}\");\n", .{out_name});
    }

    // A run that selected nothing must not look like a run that passed.
    if (tests == 0 and !rejected) {
        if (tag_text) |text| die(
            "no scenario matches -Dtags=\"{s}\"; searched {d} feature file(s) under {s}",
            .{ text, names.items.len, searched },
        );
        die(
            "no scenarios to run; searched {d} feature file(s) under {s}",
            .{ names.items.len, searched },
        );
    }

    try root.appendSlice(arena, "}\n");
    try out_dir.writeFile(aio, .{ .sub_path = "root.zig", .data = root.items });
}

/// Source that stops the compiler with `diag`, for a feature file the
/// generator cannot turn into tests. Written rather than reported so the
/// mistake lands beside the compile errors of the user's own step
/// definitions, naming the feature file and line.
fn rejection(arena: Allocator, path: []const u8, diag: anytype) Allocator.Error![]const u8 {
    const message = try std.fmt.allocPrint(arena, "{f}", .{diag});
    return std.fmt.allocPrint(
        arena,
        "// Generated by cucumber-zig from {s}. Do not edit.\ncomptime {{ @compileError(\"{f}\"); }}\n",
        .{ path, std.zig.fmtString(message) },
    );
}

/// `path` made relative to the directory the generator runs in, which is the
/// project root, so that a reported path is one the user can open from there.
fn relativize(arena: Allocator, cwd: ?[]const u8, path: []const u8) Allocator.Error![]const u8 {
    const root = cwd orelse return path;
    if (!std.fs.path.isAbsolute(path)) return path;
    const rel = try std.fs.path.relative(arena, root, null, root, path);
    if (rel.len == 0 or std.mem.startsWith(u8, rel, "..")) return path;
    return rel;
}

/// A mistake in the build's own inputs, which no feature file is to blame for.
fn die(comptime fmt: []const u8, args: anytype) noreturn {
    std.debug.print("error: " ++ fmt ++ "\n", args);
    std.process.exit(1);
}
